export const projects = [
    {
        title: "TikTok Video Generator",
        page: "tiktok-video-generator",
        src: "tiktok.jpeg",
        languages: [["Python"], ["MoviePy"], ["ZenQuote API"]],
        code: "https://github.com/liaozhuzhu/TikTokQuoteVideoGenerator",
        time: "2:56",
    },
    {
        title: "Clask",
        page: "clask",
        src: "clask.png",
        languages: [["Python"], ["Flask"], ["MySQL"], ["AssemblyAI"]],
        code: "https://github.com/liaozhuzhu/clask",
        time: "3:32",
    },
    {
        title: "My Portfolio",
        page: "my-portfolio",
        src: "home.png",
        languages: [["Vue"]],
        code: "https://github.com/liaozhuzhu/portfolio",
        time: "1:46",
    },
    {
        title: "QiT",
        page: "qit",
        src: "qit.png",
        languages: [["Python"], ["Flask"], ["MySQL"], ["Jinja"]],
        code: "https://github.com/liaozhuzhu/qit",
        time: "3:45",
    },
    {
        title: "UIowa Course Search Clone",
        page: "uiowa-course-search-clone",
        src: "iowa.png",
        languages: [["Vue"], ["Maui API"]],
        code: "https://github.com/liaozhuzhu/its-project",
        time: "2:13",
    },
    {
        title: "Sorting Visualizer",
        page: "sorting-visualizer",
        src: "sort.png",
        languages: [["JavaScript"], ["HTML/CSS"]],
        code: "https://github.com/liaozhuzhu/sort",
        time: "4:10",
    },
    {
        title: "Statipy",
        page: "statipy",
        src: "statipy.png",
        languages: [["Python"], ["Discord API"], ["Spotify API"]],
        code: "https://github.com/liaozhuzhu/statipy",
        time: "3:20",
    },
]